### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by jschwartzenberg** [unfs3/unfs3#12]
Is IPv6 supported? I tried several variants to put in a subnet in `/etc/exports`, but each time I get `syntax error in '/etc/exports', exporting nothing`.

IPv4 addresses are working fine.

**Comment by CendioOssman** [comment]
No, I'm afraid the code only supports IPv4 right now.

**Comment by CendioOssman** [comment]
IPv6 now works as #17 is merged.
