### ISSUE TITLE
unfs3 doesn't build with glibc 2.26+ or libtirpc

### ISSUE THREAD

**Issue by CendioOssman** [unfs3/unfs3#13]
glibc has dropped Sun RPC routines and now expects people to use libtirpc instead. However unfs3 fails to build with that as well as we make some assumptions that everything is IPv4.

**Comment by rafal-prasal** [comment]
in rhel in CodeReady Builder and Centos8 Powertools you may find
rpcsvc-proto-devel

Name         : rpcsvc-proto-devel
Version      : 1.3.1
Release      : 4.el8
Architecture : x86_64
Size         : 30 k
Source       : rpcsvc-proto-1.3.1-4.el8.src.rpm
Repository   : codeready-builder-for-rhel-8-x86_64-rpms
Summary      : RPC protocol definitions
URL          : https://github.com/thkukuk/rpcsvc-proto
License      : BSD and LGPLv2+
Description  : The rpcsvc-proto package includes several rpcsvc header files
             : and RPC protocol definitions from SunRPC sources (as shipped with
             : glibc).

which delivers sunrpc libs for unfs3 compilation

**Comment by cjcj5243** [comment]
> in rhel in CodeReady Builder and Centos8 Powertools you may find
> rpcsvc-proto-devel
> 
> Name : rpcsvc-proto-devel
> Version : 1.3.1
> Release : 4.el8
> Architecture : x86_64
> Size : 30 k
> Source : rpcsvc-proto-1.3.1-4.el8.src.rpm
> Repository : codeready-builder-for-rhel-8-x86_64-rpms
> Summary : RPC protocol definitions
> URL : https://github.com/thkukuk/rpcsvc-proto
> License : BSD and LGPLv2+
> Description : The rpcsvc-proto package includes several rpcsvc header files
> : and RPC protocol definitions from SunRPC sources (as shipped with
> : glibc).
> 
> which delivers sunrpc libs for unfs3 compilation

I have already installed rpcsvc-proto-devel on centos8, but it still dones't work for building unfs3, the error is as follows:
`./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ar... ar
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for bison... bison -y
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for library containing xdr_int... no
checking for library containing socket... none required
checking for library containing inet_aton... none required
checking for mntent.h... yes
checking for stdint.h... yes
checking for sys/mnttab.h... no
checking for sys/mount.h... yes
checking for sys/vmount.h... no
checking for rpc/svc_soc.h... no
checking for linux/ext2_fs.h... no
checking for int32... no
checking for uint32... no
checking for int64... no
checking for uint64... no
checking for struct stat.st_gen... no
checking for struct __rpc_svcxprt.xp_fd... no
checking for xdr_int... no
checking for xdr_u_int... no
checking for xdr_int32... no
checking for xdr_int32_t... no
checking for xdr_uint32... no
checking for xdr_uint32_t... no
checking for xdr_u_int32_t... no
checking for xdr_uint64... no
checking for xdr_uint64_t... no
checking for xdr_u_int64_t... no
checking for svc_getreq_poll... no
checking for statvfs... yes
checking for seteuid... yes
checking for setegid... yes
checking for setresuid... yes
checking for setresgid... yes
checking for vsyslog... yes
checking for lchown... yes
checking for setgroups... yes
checking for svc_tli_create... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating Config/Makefile
config.status: creating Extras/Makefile
config.status: creating config.h
config.status: config.h is unchanged
[root@localhost unfs3]# make
for i in Config ; do (cd $i && make all) || exit; done
make[1]: Entering directory '/root/unfs3/Config'
gcc -g -O2 -Wall -W -I.. -I. -I..   -c -o lex.yy.o lex.yy.c
./exports.l:9:10: fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>
          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: lex.yy.o] Error 1
make[1]: Leaving directory '/root/unfs3/Config'
make: *** [Makefile:38: subdirs] Error 2
`

**Comment by CendioOssman** [comment]
#17 is now ready for testing, if you have the time.

**Comment by Komic** [comment]
https://github.com/unfs3/unfs3/commit/3fa0568e6ef96e045286afe18444bc28fe93962b compiled successfully with 2.31.

**Comment by CendioOssman** [comment]
Huh? So what is providing the rpc headers on your system?

**Comment by Komic** [comment]
I can't reproduce anymore. That night is a bit of a blur right now so I'm probably completely wrong, my bad. Thanks for your work though, unfs3 saved my ass. (:
