### ISSUE TITLE
Dependencies and error with make

### ISSUE THREAD

**Issue by kaiyazeera** [unfs3/unfs3#22]
On Ubuntu, `unfs3` has dependencies on  `autoconf flex gcc bison make`.
Consider adding them. 

Occurs without `sudo`: 
```
make install
/usr/bin/install -c -d /usr/local/sbin
/usr/bin/install -c -d /usr/local/share/man/man7
/usr/bin/install: cannot change permissions of ‘/usr/local/share/man/man7’: No such file or directory
make: *** [Makefile:42: install] Error 1
```
Given that this is userspace-nfs, you might consider adding  a hint whether sudo is required or not and whether installation with sudo is safe and secure or breaks stuff.

**Comment by CendioOssman** [comment]
sudo is always required to install any program system wide, so I think it is excessive to explicitly mention standard things such as that.

Installing it system wide should be fine.

**Comment by kaiyazeera** [comment]
if i has sudo permissions I would ues standard nfs ^^'
