### ISSUE TITLE
nfs server is out-of-order

### ISSUE THREAD

**Issue by HeroKern** [unfs3/unfs3#37]
For nfs client read request is disordered I think how to handle the order?

**Comment by HeroKern** [comment]
i  use this nfs sever for fuse file system

**Comment by CendioOssman** [comment]
I'm afraid I don't understand the issue you are encountering. Could you please describe in detail what you are doing, what is happening, and what you expected to happen?

**Comment by HeroKern** [comment]
> I'm afraid I don't understand the issue you are encountering. Could you please describe in detail what you are doing, what is happening, and what you expected to happen?

I hope this nfsproc3_read_3_svc function is order   , argp->offset is order,Now that argp-> offset is not an increase in order。

**Comment by CendioOssman** [comment]
I'm afraid that indicates some issue with the NFS client, not the server. That offset is given by the client to the server where the client wants data read. You'll need to file a bug with your NFS client if it keeps resending the same offset in each request.
