### ISSUE TITLE
What local and remote file system can be exported?

### ISSUE THREAD

**Issue by eppesuig** [unfs3/unfs3#39]
Hello,
I know that NFS from linux kernel can only export local file systems, while I read that unfsd may also export AFS file systems. Does this means that many remote file system are exportable? Does unfsd exports mounted cifs file systems?

Thank you,
Giuseppe

**Comment by CendioOssman** [comment]
It should in theory be able to export anything. There might be some corner cases that misbehave if the filesystem does something weird, though. E.g. FAT doesn't have stable inode numbers, which we've had to add workarounds for.

I'm not aware of any issues with CIFS, so it should hopefully work just fine.
