### ISSUE TITLE
PKG_CHECK_MODULES error

### ISSUE THREAD

**Issue by herok94** [unfs3/unfs3#41]
I exec ./configure  cmd using ubuntu22.04 and got the following error:
./configure: line 4525: syntax error near unexpected token `TIRPC,'
./configure: line 4525: `PKG_CHECK_MODULES(TIRPC, libtirpc)'

**Comment by HeroKern** [comment]
I delete this PKG_CHECK_MODULES(TIRPC, libtirpc) line and it works

**Comment by CendioOssman** [comment]
It sounds like the `configure` script was not generated correctly.

How was unfs3 downloaded and built? Please try to include the exact steps so I see if I can get the same error here.

**Comment by eliphatfs** [comment]
I have met the same problem. In a clean ubuntu docker, I apt-installed bison, flex and autoconf, then git-cloned this repository, then run ./bootstrap and ./configure, and it goes like that.

**Comment by eliphatfs** [comment]
After I removed the line I still cannot get it compiled.
```
daemon.c:143:45: error: 'struct sockaddr_in' has no member named 'sin6_port'; did you mean 'sin_port'?
```

**Comment by eliphatfs** [comment]
I can compile 0.9.23 version, and can configure (but not compile) 0.10.0 version, and cannot configure the master version.

**Comment by CendioOssman** [comment]
I would guess that pkg-config is not installed. Could you install that package on your docker instance and repeat the whole procedure?

**Comment by CendioOssman** [comment]
No response. Closing.
