### ISSUE TITLE
mount.nfs: mount system call failed for /mnt

### ISSUE THREAD

**Issue by megastallman** [unfs3/unfs3#42]
Hi there!

I'm trying UNFS3 on Kubuntu 24.04. It builds, starts but no way to mount the share.

My exports file:
```
/srv    192.168.1.0/24(rw,no_root_squash)
```

My server command:
```
# /opt/unfs3/prefix/sbin/unfsd -d -e /opt/unfs3/prefix/exports
```

Client(same machine):
```
# mount -t nfs -o nfsvers=3 192.168.1.5:/srv /mnt
mount.nfs: mount system call failed for /mnt
```

Please help. Maybe I'm missing some options.

**Comment by CendioOssman** [comment]
That error message looks like some kernel issue rather than a server issue, unfortunately.

Could you try a mount from a different machine?

**Comment by megastallman** [comment]
Thanks @CendioOssman !
I've tried to mount on another host, and mount was successfull. The actual problem was Opensnitch, my application firewall, that I had to disable to make NFS work.
I've also added "no_root_squash" to my exports file, and that is the actual configuration I'm using now.
