### ISSUE TITLE
how to build unfs3 from source?

### ISSUE THREAD

**Issue by tenox7** [unfs3/unfs3#45]
```
unfs3-0.10.0 $ ./bootstrap 
configure.ac:3: warning: The macro 'AC_CONFIG_HEADER' is obsolete.
configure.ac:3: You should run autoupdate.
./lib/autoconf/status.m4:719: AC_CONFIG_HEADER is expanded from...
configure.ac:3: the top level
configure.ac:7: warning: AC_PROG_LEX without either yywrap or noyywrap is obsolete
./lib/autoconf/programs.m4:743: _AC_PROG_LEX is expanded from...
./lib/autoconf/programs.m4:736: AC_PROG_LEX is expanded from...
configure.ac:7: the top level
configure.ac:12: warning: The macro 'AC_HEADER_STDC' is obsolete.
configure.ac:12: You should run autoupdate.
./lib/autoconf/headers.m4:663: AC_HEADER_STDC is expanded from...
configure.ac:12: the top level
```

do I need an older linux distro for this? what did you build the release on?
thanks!

**Comment by CendioOssman** [comment]
Using a release is the recommended way, as you don't have to deal with generating the configure script.

If you want to build from git, you'll indeed need to run `./bootstrap`. All of those things are warnings, though. So I don't quite understand where you are stuck?

**Comment by tenox7** [comment]
I tried both. Always getting some errors. Let me try different linux distro. I just wanted to check if you using something specific.

**Comment by tenox7** [comment]
ok got it build on ubuntu
thanks!
