### ISSUE TITLE
Question regarding logging

### ISSUE THREAD

**Issue by BigCaber** [unfs3/unfs3#48]
Hi

I am researching the logging capability of NFS and found that original NFS does kernel level logging, which is fine. However I am wondering the logging capability and ease of access to logs of unfs3 ? (NFS required some extra configuration to enable kernel logging)

Thanks !!

**Comment by CendioOssman** [comment]
unfsd logs to syslog when running as a daemon ("detached"), and to stderr when running in the foreground.

Is there something specific you are interested in?

**Comment by BigCaber** [comment]
I am looking for auth, access logs to nfs directory, basically watch it like a Windows File Server and to be able to see what happens inside.

**Comment by CendioOssman** [comment]
I'm afraid unfsd does not log such things. It pretty much only logs when something goes wrong. So it will not help out much for auditing.

This is not too unlike the Linux kernel NFS server, which also has fairly little logging. NFS is largely built on a higher trust than e.g. SMB.
