### ISSUE TITLE
Can't find aarch64 compiled version of 0.10 binary

### ISSUE THREAD

**Issue by tuhajbej6** [unfs3/unfs3#50]
Hi,

Kindly can I ask someone to provide a compiled version for aarch64 architecture of the latest version 0.10 ?

I am already using older version 0.9.23.

Use is for **LibreElec** with Python3 - a much read-only distro that allows only Entware (https://www.artembutusov.com/libreelec-entware-ng-installation/) software to be installed - yet this package is outdated.

Some dependencies below:

```
kodi:~ # ll /opt/sbin/unfsd
-rwxr-xr-x    1 root     root         97320 Feb  8  2024 /opt/sbin/unfsd
kodi:~ # /opt/bin/ldd /opt/sbin/unfsd
        linux-vdso.so.1 (0x0000ffffa3db9000)
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0x0000ffffa3d68000)
        libc.so.6 => /opt/lib/libc.so.6 (0x0000ffffa3bf9000)
        /opt/lib/ld-linux-aarch64.so.1 (0x0000ffffa3d8b000)

```

**Comment by CendioOssman** [comment]
I'm afraid that we do not provide any binaries. You'll need to either build unfs3 yourself, or request that LibreElec builds it for you.
